# Generated by Django 3.0.7 on 2020-06-22 18:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(help_text='First Name of the Patient', max_length=150)),
                ('last_name', models.CharField(blank=True, help_text='Last Name of the Patient', max_length=150, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('date_of_joined', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
