# Generated by Django 3.0.7 on 2020-06-22 19:55

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20200623_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientlogmodel',
            name='consulted_on',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='patientlogmodel',
            name='created_on',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='patientlogmodel',
            name='date_of_joined',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='date_of_joined',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now, null=True),
        ),
    ]
