# Generated by Django 3.0.7 on 2020-06-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patientmodel_patient_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientlogmodel',
            name='patient_id',
            field=models.CharField(blank=True, help_text='patient id', max_length=500, null=True),
        ),
    ]
