# Generated by Django 3.0.7 on 2020-06-26 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patientlogmodel_patient_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientmodel',
            name='patient_log',
        ),
    ]
