# Generated by Django 3.0.7 on 2020-06-26 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_remove_patientmodel_patient_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientlogmodel',
            old_name='patient_id',
            new_name='patient_uuid',
        ),
    ]
