# Generated by Django 3.0.7 on 2020-06-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_auto_20200626_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmodel',
            name='aadhar_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='email_id',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='gender',
            field=models.CharField(default='male', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='guardian_relation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='mobile_number',
            field=models.CharField(default='999999999', max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='patient_op_id',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='profession',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
