# Generated by Django 3.0.7 on 2020-06-26 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_auto_20200626_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='')),
                ('patient_old_records', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='patient_old_records', to='patients.PatientModel')),
            ],
        ),
    ]
