# Generated by Django 3.0.7 on 2020-06-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_imagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='images',
            field=models.ImageField(upload_to='patientoldrecords/'),
        ),
    ]
