# Generated by Django 3.0.7 on 2020-06-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_auto_20200627_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmodel',
            name='height',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='weight',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
