# Generated by Django 3.0.7 on 2020-06-27 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_patientmodel_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientlogmodel',
            name='patient_model',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='patient_logs', to='patients.PatientModel'),
        ),
    ]
