# Generated by Django 3.0.7 on 2020-06-27 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_patientlogmodel_patient_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientlogmodel',
            name='patient_model',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient_logs', to='patients.PatientModel'),
        ),
    ]
