# Generated by Django 3.0.7 on 2020-07-02 07:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_auto_20200627_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientmodel',
            old_name='patientprofile',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='patientmodel',
            old_name='mobile_number',
            new_name='mobile',
        ),
        migrations.RemoveField(
            model_name='patientmodel',
            name='uuid',
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='treatment',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
