# Generated by Django 3.0.7 on 2020-07-02 07:26

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_auto_20200702_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmodel',
            name='date',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now),
        ),
    ]
