# Generated by Django 3.0.7 on 2020-07-02 07:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0017_auto_20200702_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmodel',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
