# Generated by Django 3.0.7 on 2020-07-02 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0019_auto_20200702_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientmodel',
            name='uuid',
        ),
    ]
