# Generated by Django 3.0.7 on 2020-07-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0020_remove_patientmodel_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmodel',
            name='bGroup',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='bPresure',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='injury',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='marital_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='sugger',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
