# Generated by Django 3.0.7 on 2020-07-11 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0021_auto_20200712_0136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientmodel',
            old_name='patient_op_id',
            new_name='patient_op',
        ),
    ]
