# Generated by Django 3.0.7 on 2020-07-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0022_auto_20200712_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmodel',
            name='dob',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
