# Generated by Django 3.0.7 on 2020-07-11 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0023_patientmodel_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientmodel',
            old_name='email_id',
            new_name='email',
        ),
    ]
