# Generated by Django 3.0.7 on 2020-07-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0025_auto_20200712_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmodel',
            name='doc_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
