# Generated by Django 3.0.7 on 2020-07-13 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0026_patientmodel_doc_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientlogmodel',
            old_name='patient_uuid',
            new_name='patient_id',
        ),
        migrations.RemoveField(
            model_name='patientlogmodel',
            name='patient_model',
        ),
    ]
