# Generated by Django 3.0.7 on 2020-07-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0027_auto_20200714_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmodel',
            name='about',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='about_patient',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
