# Generated by Django 3.0.7 on 2020-07-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0028_auto_20200714_0218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientlogmodel',
            name='description',
        ),
        migrations.AddField(
            model_name='patientlogmodel',
            name='Treatment',
            field=models.CharField(blank=True, help_text='Treatment', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='patientlogmodel',
            name='session_log',
            field=models.FileField(blank=True, null=True, upload_to='patientlogs/'),
        ),
        migrations.AlterField(
            model_name='patientlogmodel',
            name='log_documents',
            field=models.FileField(blank=True, null=True, upload_to='patientoldlogs/'),
        ),
    ]
