# Generated by Django 3.0.7 on 2020-07-14 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0029_auto_20200715_0304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientlogmodel',
            old_name='Treatment',
            new_name='treatment',
        ),
    ]
