# Generated by Django 3.0.7 on 2020-08-01 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0030_auto_20200715_0311'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('stid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='entername', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='studentimages',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('text', models.CharField(blank=True, help_text='enter', max_length=200, null=True)),
                ('stid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentimages', to='patients.StudentModel')),
            ],
        ),
    ]
