# Generated by Django 3.0.7 on 2020-09-09 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0031_studentimages_studentmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientmodel',
            name='age',
        ),
    ]
