# Generated by Django 3.0.7 on 2020-09-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0033_auto_20200910_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientlogmodel',
            name='session_log',
            field=models.CharField(blank=True, help_text='patient streamdata', max_length=500, null=True),
        ),
    ]
