# Generated by Django 3.0.7 on 2020-09-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0034_auto_20200916_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientlogmodel',
            name='session_log',
            field=models.CharField(blank=True, help_text='patient stream data', max_length=500, null=True),
        ),
    ]
