# Generated by Django 3.0.7 on 2020-09-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0035_auto_20200916_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientmodel',
            old_name='sugger',
            new_name='haemoglobin',
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='heartbeat',
            field=models.CharField(blank=True, default='80', max_length=100),
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='sugar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='bpresure',
            field=models.CharField(blank=True, default='80', max_length=100),
        ),
    ]
