# Generated by Django 3.0.6 on 2020-05-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.CharField(default=0.0010453253052349891, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
