# Generated by Django 3.0.7 on 2020-06-26 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_userprofile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_pic',
        ),
    ]
