# Generated by Django 3.0.7 on 2020-07-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_remove_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='doctorprofile/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='specialist',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
