# Generated by Django 3.0.7 on 2020-07-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_auto_20200713_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='img',
            field=models.ImageField(blank=True, default='doctorprofile/defaultdoctor.jpg', null=True, upload_to='doctorprofile/'),
        ),
    ]
