# Generated by Django 3.0.7 on 2020-09-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0009_remove_userprofile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='camera_ip_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wsport',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table=None,
        ),
    ]
