# Generated by Django 3.0.7 on 2020-09-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0010_auto_20200918_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pic',
            field=models.ImageField(blank=True, upload_to='userprofile'),
        ),
    ]
