# Generated by Django 3.0.7 on 2020-09-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0012_auto_20200918_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pic',
            field=models.ImageField(blank=True, default='default/defaultdoctor.jpg', null=True, upload_to='userprofile/'),
        ),
    ]
