# Generated by Django 3.0.7 on 2020-09-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0015_auto_20200919_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='wsport',
            field=models.TextField(blank=True, default='9999'),
        ),
    ]
