# Generated by Django 3.0.7 on 2020-09-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0016_auto_20200919_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='camera_ip_address',
            field=models.TextField(blank=True, default='192.168.1.121', null=True),
        ),
    ]
